AWSTemplateFormatVersion: '2010-09-09'
Description: An AWS Serverless Specification template describing your function.
Resources:
  GuardDetectCW2DDB:
    Properties:
      CodeUri: s3://elltdev.lambda.lotte.net/aaeab5cc0cdda159f04a35f26705214d
      Description: ''
      Environment:
        Variables:
          DEBUG_LOG: true
      Events:
        CloudWatchEvent1:
          Properties:
            Pattern:
              detail-type:
              - GuardDuty Finding
              source:
              - aws.guardduty
          Type: CloudWatchEvent
      FunctionName: GUARD-DETECT-CW-2-DDB
      Handler: index.handler
      MemorySize: 128
      Role: arn:aws:iam::515303172277:role/LambdaExecute
      Runtime: nodejs8.10
      Timeout: 60
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
